image:
  repository: ghcr.io/panixida-infrastructure/telegram-alert-gateway/api
  tag: production-21

migrations:
  image:
    repository: ghcr.io/panixida-infrastructure/telegram-alert-gateway/ef-migrator
    tag: production-21
