image:
  repository: ghcr.io/panixida-infrastructure/telegram-alert-gateway/api
  tag: production-15

migrations:
  image:
    repository: ghcr.io/panixida-infrastructure/telegram-alert-gateway/ef-migrator
    tag: production-15
