image:
  repository: ghcr.io/panixida-infrastructure/telegram-alert-gateway/api
  tag: "0"

migrations:
  image:
    repository: ghcr.io/panixida-infrastructure/telegram-alert-gateway/ef-migrator
    tag: "0"
