<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Shouldly" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
        <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
        <PackageReference Include="xunit.v3.mtp-v2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\Module\PANiXiDA.TelegramAlertGateway.Notifications.Application\PANiXiDA.TelegramAlertGateway.Notifications.Application.csproj" />
        <ProjectReference Include="..\..\..\src\Module\PANiXiDA.TelegramAlertGateway.Notifications.Domain\PANiXiDA.TelegramAlertGateway.Notifications.Domain.csproj" />
        <ProjectReference Include="..\..\..\src\Module\PANiXiDA.TelegramAlertGateway.Notifications.Infrastructure\PANiXiDA.TelegramAlertGateway.Notifications.Infrastructure.csproj" />
        <ProjectReference Include="..\..\..\src\Module\PANiXiDA.TelegramAlertGateway.Notifications.Presentation\PANiXiDA.TelegramAlertGateway.Notifications.Presentation.csproj" />
        <ProjectReference Include="..\..\PANiXiDA.TelegramAlertGateway.Testing\PANiXiDA.TelegramAlertGateway.Testing.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="PANiXiDA.Core.Application.Persistence" />
        <Using Include="PANiXiDA.Core.Application.Querying.Pagination" />
        <Using Include="PANiXiDA.Core.Application.Querying.Sorting" />
        <Using Include="PANiXiDA.Core.Infrastructure.Persistence.Ef.Constants" />

        <Using Include="Shouldly" />
        <Using Include="Xunit" />
    </ItemGroup>
</Project>
