// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PANiXiDA.TelegramAlertGateway.Notifications.Infrastructure.Persistence.Core;

#nullable disable

namespace PANiXiDA.TelegramAlertGateway.Notifications.Infrastructure.Persistence.Core.Migrations
{
    [DbContext(typeof(NotificationsWriteDbContext))]
    [Migration("20260901191532_2026-09-01_19-15-32_Rename_Column_status_In_notifications_Table_To_delivery_CBBC6FC1")]
    partial class _20260901_191532_Rename_Column_status_In_notifications_Table_To_delivery_CBBC6FC1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseHiLo(modelBuilder, "EntityFrameworkHiLoSequence");

            modelBuilder.HasSequence("EntityFrameworkHiLoSequence")
                .IncrementsBy(10);

            modelBuilder.Entity("PANiXiDA.TelegramAlertGateway.Notifications.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasColumnOrder(3);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kind");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(3900)
                        .HasColumnType("character varying(3900)")
                        .HasColumnName("message");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("topic");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(2);

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_notifications_key");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("PANiXiDA.TelegramAlertGateway.Notifications.Infrastructure.VictoriaLogs.LogIngestionCheckpoint", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("NextWindowStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_window_start_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_log_ingestion_checkpoints");

                    b.ToTable("log_ingestion_checkpoints", (string)null);
                });

            modelBuilder.Entity("PANiXiDA.TelegramAlertGateway.Notifications.Domain.Notifications.Notification", b =>
                {
                    b.OwnsOne("PANiXiDA.TelegramAlertGateway.Notifications.Domain.Notifications.ValueObjects.NotificationDelivery", "Delivery", b1 =>
                        {
                            b1.Property<Guid>("NotificationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Attempts")
                                .HasColumnType("integer")
                                .HasColumnName("delivery_attempts");

                            b1.Property<DateTimeOffset>("AvailableAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("delivery_available_at_utc");

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("delivery_created_at_utc");

                            b1.Property<string>("LastError")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("delivery_last_error");

                            b1.Property<DateTimeOffset?>("SentAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("delivery_sent_at_utc");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("delivery_status");

                            b1.HasKey("NotificationId");

                            b1.HasIndex("Status", "AvailableAtUtc")
                                .HasDatabaseName("ix_notifications_delivery_status_delivery_available_at_utc");

                            b1.HasIndex("Status", "SentAtUtc")
                                .HasDatabaseName("ix_notifications_delivery_status_delivery_sent_at_utc");

                            b1.ToTable("notifications");

                            b1.WithOwner()
                                .HasForeignKey("NotificationId")
                                .HasConstraintName("fk_notifications_notifications_id");
                        });

                    b.Navigation("Delivery")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
